"""
Django settings for ll_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p9o2j=_y&r3ji(5w=w!w4ke&x1=m%t#$v6by%d$)_)612n+@18'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    #我的应用程序
    'learning_logs',
    'accounts',
    #第三方应用程序
    'django_bootstrap5',
    'markdownify',
    #默认添加的应用程序
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'll_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'll_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# 如果你用项目级 static 目录
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 我的设置
LOGIN_REDIRECT_URL='learning_logs:index'
LOGOUT_REDIRECT_URL='learning_logs:index'
LOGIN_URL='accounts:login'

# 可选：限制允许的 HTML 标签/属性（更安全）
MARKDOWNIFY = {
    "default": {
        # 关键：开启 fenced_code + codehilite
        "MARKDOWN_EXTENSIONS": [
            "fenced_code",
            "codehilite",
            "markdown.extensions.tables", 
        ],
        "MARKDOWN_EXTENSION_CONFIGS": {
            "codehilite": {
                "guess_lang": False,
                "noclasses": False,  # 用 class（配合 codehilite.css）
            }
        },

        # 关键：白名单要允许 codehilite 用到的标签/属性
        "WHITELIST_TAGS": [
            "div",
            "p","a","strong","em","ul","ol","li",
            "pre","code","span",   # span 必须允许，否则高亮会被清洗掉
            "table","thead","tbody","tr","th","td",
            
        ],
        "WHITELIST_ATTRS": {
            "a": ["href", "title", "rel"],
            "*": ["class"],        # class 必须允许，否则 codehilite/language-xxx 会被清掉
        },
    }
}


# Platform.sh设置
from platformshconfig import Config
config=Config()
if config.is_valid_platform():
    ALLOWED_HOSTS.append(".platformsh.site")
    if config.appDir:
        STATIC_ROOT=BASE_DIR/'static'
    if config.projectEntropy:
        SECRET_KEY=config.projectEntropy
    if not config.in_build():
        db_settings=config.credentials("database")
        DATABASES={
            'default':{
                'ENGINE':'django.db.backends.postgresql',
                'NAME':db_settings['path'],
                'USER':db_settings['username'],
                'PASSWORD':db_settings['password'],
                'HOST':db_settings['host'],
                'PORT':db_settings['port'],
            },
        }
        